// Code generated by fastssz. DO NOT EDIT.
// Hash: a1e27fd6406cf3f3b0722e27a9b705163f641366dfc81408b1e56dffac7179cf
// Version: 0.1.3
package types

import (
	"github.com/attestantio/go-eth2-client/spec"
	"github.com/attestantio/go-eth2-client/spec/altair"
	"github.com/attestantio/go-eth2-client/spec/phase0"
	ssz "github.com/ferranbt/fastssz"
)

// MarshalSSZ ssz marshals the AssignedAggregator object
func (a *AssignedAggregator) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(a)
}

// MarshalSSZTo ssz marshals the AssignedAggregator object to a target array
func (a *AssignedAggregator) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf

	// Field (0) 'ValidatorIndex'
	dst = ssz.MarshalUint64(dst, uint64(a.ValidatorIndex))

	// Field (1) 'SelectionProof'
	dst = append(dst, a.SelectionProof[:]...)

	// Field (2) 'CommitteeIndex'
	dst = ssz.MarshalUint64(dst, a.CommitteeIndex)

	return
}

// UnmarshalSSZ ssz unmarshals the AssignedAggregator object
func (a *AssignedAggregator) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size != 112 {
		return ssz.ErrSize
	}

	// Field (0) 'ValidatorIndex'
	a.ValidatorIndex = phase0.ValidatorIndex(ssz.UnmarshallUint64(buf[0:8]))

	// Field (1) 'SelectionProof'
	copy(a.SelectionProof[:], buf[8:104])

	// Field (2) 'CommitteeIndex'
	a.CommitteeIndex = ssz.UnmarshallUint64(buf[104:112])

	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the AssignedAggregator object
func (a *AssignedAggregator) SizeSSZ() (size int) {
	size = 112
	return
}

// HashTreeRoot ssz hashes the AssignedAggregator object
func (a *AssignedAggregator) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(a)
}

// HashTreeRootWith ssz hashes the AssignedAggregator object with a hasher
func (a *AssignedAggregator) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'ValidatorIndex'
	hh.PutUint64(uint64(a.ValidatorIndex))

	// Field (1) 'SelectionProof'
	hh.PutBytes(a.SelectionProof[:])

	// Field (2) 'CommitteeIndex'
	hh.PutUint64(a.CommitteeIndex)

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the AssignedAggregator object
func (a *AssignedAggregator) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(a)
}

// MarshalSSZ ssz marshals the AggregatorConsensusData object
func (a *AggregatorConsensusData) MarshalSSZ() ([]byte, error) {
	return ssz.MarshalSSZ(a)
}

// MarshalSSZTo ssz marshals the AggregatorConsensusData object to a target array
func (a *AggregatorConsensusData) MarshalSSZTo(buf []byte) (dst []byte, err error) {
	dst = buf
	offset := int(32)

	// Field (0) 'Version'
	dst = ssz.MarshalUint64(dst, uint64(a.Version))

	// Offset (1) 'Aggregators'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(a.Aggregators) * 112

	// Offset (2) 'CommitteeIndex'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(a.CommitteeIndex) * 8

	// Offset (3) 'Attestation'
	dst = ssz.WriteOffset(dst, offset)
	for ii := 0; ii < len(a.Attestation); ii++ {
		offset += 4
		offset += len(a.Attestation[ii])
	}

	// Offset (4) 'Contributors'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(a.Contributors) * 112

	// Offset (5) 'SubCommitteeIndexes'
	dst = ssz.WriteOffset(dst, offset)
	offset += len(a.SubCommitteeIndexes) * 8

	// Offset (6) 'SyncCommitteeSelectionProof'
	dst = ssz.WriteOffset(dst, offset)

	// Field (1) 'Aggregators'
	if size := len(a.Aggregators); size > 3000 {
		err = ssz.ErrListTooBigFn("AggregatorConsensusData.Aggregators", size, 3000)
		return
	}
	for ii := 0; ii < len(a.Aggregators); ii++ {
		if dst, err = a.Aggregators[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (2) 'CommitteeIndex'
	if size := len(a.CommitteeIndex); size > 64 {
		err = ssz.ErrListTooBigFn("AggregatorConsensusData.CommitteeIndex", size, 64)
		return
	}
	for ii := 0; ii < len(a.CommitteeIndex); ii++ {
		dst = ssz.MarshalUint64(dst, a.CommitteeIndex[ii])
	}

	// Field (3) 'Attestation'
	if size := len(a.Attestation); size > 64 {
		err = ssz.ErrListTooBigFn("AggregatorConsensusData.Attestation", size, 64)
		return
	}
	{
		offset = 4 * len(a.Attestation)
		for ii := 0; ii < len(a.Attestation); ii++ {
			dst = ssz.WriteOffset(dst, offset)
			offset += len(a.Attestation[ii])
		}
	}
	for ii := 0; ii < len(a.Attestation); ii++ {
		if size := len(a.Attestation[ii]); size > 1000000 {
			err = ssz.ErrBytesLengthFn("AggregatorConsensusData.Attestation[ii]", size, 1000000)
			return
		}
		dst = append(dst, a.Attestation[ii]...)
	}

	// Field (4) 'Contributors'
	if size := len(a.Contributors); size > 12000 {
		err = ssz.ErrListTooBigFn("AggregatorConsensusData.Contributors", size, 12000)
		return
	}
	for ii := 0; ii < len(a.Contributors); ii++ {
		if dst, err = a.Contributors[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	// Field (5) 'SubCommitteeIndexes'
	if size := len(a.SubCommitteeIndexes); size > 4 {
		err = ssz.ErrListTooBigFn("AggregatorConsensusData.SubCommitteeIndexes", size, 4)
		return
	}
	for ii := 0; ii < len(a.SubCommitteeIndexes); ii++ {
		dst = ssz.MarshalUint64(dst, a.SubCommitteeIndexes[ii])
	}

	// Field (6) 'SyncCommitteeSelectionProof'
	if size := len(a.SyncCommitteeSelectionProof); size > 4 {
		err = ssz.ErrListTooBigFn("AggregatorConsensusData.SyncCommitteeSelectionProof", size, 4)
		return
	}
	for ii := 0; ii < len(a.SyncCommitteeSelectionProof); ii++ {
		if dst, err = a.SyncCommitteeSelectionProof[ii].MarshalSSZTo(dst); err != nil {
			return
		}
	}

	return
}

// UnmarshalSSZ ssz unmarshals the AggregatorConsensusData object
func (a *AggregatorConsensusData) UnmarshalSSZ(buf []byte) error {
	var err error
	size := uint64(len(buf))
	if size < 32 {
		return ssz.ErrSize
	}

	tail := buf
	var o1, o2, o3, o4, o5, o6 uint64

	// Field (0) 'Version'
	a.Version = spec.DataVersion(ssz.UnmarshallUint64(buf[0:8]))

	// Offset (1) 'Aggregators'
	if o1 = ssz.ReadOffset(buf[8:12]); o1 > size {
		return ssz.ErrOffset
	}

	if o1 != 32 {
		return ssz.ErrInvalidVariableOffset
	}

	// Offset (2) 'CommitteeIndex'
	if o2 = ssz.ReadOffset(buf[12:16]); o2 > size || o1 > o2 {
		return ssz.ErrOffset
	}

	// Offset (3) 'Attestation'
	if o3 = ssz.ReadOffset(buf[16:20]); o3 > size || o2 > o3 {
		return ssz.ErrOffset
	}

	// Offset (4) 'Contributors'
	if o4 = ssz.ReadOffset(buf[20:24]); o4 > size || o3 > o4 {
		return ssz.ErrOffset
	}

	// Offset (5) 'SubCommitteeIndexes'
	if o5 = ssz.ReadOffset(buf[24:28]); o5 > size || o4 > o5 {
		return ssz.ErrOffset
	}

	// Offset (6) 'SyncCommitteeSelectionProof'
	if o6 = ssz.ReadOffset(buf[28:32]); o6 > size || o5 > o6 {
		return ssz.ErrOffset
	}

	// Field (1) 'Aggregators'
	{
		buf = tail[o1:o2]
		num, err := ssz.DivideInt2(len(buf), 112, 3000)
		if err != nil {
			return err
		}
		a.Aggregators = make([]AssignedAggregator, num)
		for ii := 0; ii < num; ii++ {
			if err = a.Aggregators[ii].UnmarshalSSZ(buf[ii*112 : (ii+1)*112]); err != nil {
				return err
			}
		}
	}

	// Field (2) 'CommitteeIndex'
	{
		buf = tail[o2:o3]
		num, err := ssz.DivideInt2(len(buf), 8, 64)
		if err != nil {
			return err
		}
		a.CommitteeIndex = ssz.ExtendUint64(a.CommitteeIndex, num)
		for ii := 0; ii < num; ii++ {
			a.CommitteeIndex[ii] = ssz.UnmarshallUint64(buf[ii*8 : (ii+1)*8])
		}
	}

	// Field (3) 'Attestation'
	{
		buf = tail[o3:o4]
		num, err := ssz.DecodeDynamicLength(buf, 64)
		if err != nil {
			return err
		}
		a.Attestation = make([][]byte, num)
		err = ssz.UnmarshalDynamic(buf, num, func(indx int, buf []byte) (err error) {
			if len(buf) > 1000000 {
				return ssz.ErrBytesLength
			}
			if cap(a.Attestation[indx]) == 0 {
				a.Attestation[indx] = make([]byte, 0, len(buf))
			}
			a.Attestation[indx] = append(a.Attestation[indx], buf...)
			return nil
		})
		if err != nil {
			return err
		}
	}

	// Field (4) 'Contributors'
	{
		buf = tail[o4:o5]
		num, err := ssz.DivideInt2(len(buf), 112, 12000)
		if err != nil {
			return err
		}
		a.Contributors = make([]AssignedAggregator, num)
		for ii := 0; ii < num; ii++ {
			if err = a.Contributors[ii].UnmarshalSSZ(buf[ii*112 : (ii+1)*112]); err != nil {
				return err
			}
		}
	}

	// Field (5) 'SubCommitteeIndexes'
	{
		buf = tail[o5:o6]
		num, err := ssz.DivideInt2(len(buf), 8, 4)
		if err != nil {
			return err
		}
		a.SubCommitteeIndexes = ssz.ExtendUint64(a.SubCommitteeIndexes, num)
		for ii := 0; ii < num; ii++ {
			a.SubCommitteeIndexes[ii] = ssz.UnmarshallUint64(buf[ii*8 : (ii+1)*8])
		}
	}

	// Field (6) 'SyncCommitteeSelectionProof'
	{
		buf = tail[o6:]
		num, err := ssz.DivideInt2(len(buf), 160, 4)
		if err != nil {
			return err
		}
		a.SyncCommitteeSelectionProof = make([]altair.SyncCommitteeContribution, num)
		for ii := 0; ii < num; ii++ {
			if err = a.SyncCommitteeSelectionProof[ii].UnmarshalSSZ(buf[ii*160 : (ii+1)*160]); err != nil {
				return err
			}
		}
	}
	return err
}

// SizeSSZ returns the ssz encoded size in bytes for the AggregatorConsensusData object
func (a *AggregatorConsensusData) SizeSSZ() (size int) {
	size = 32

	// Field (1) 'Aggregators'
	size += len(a.Aggregators) * 112

	// Field (2) 'CommitteeIndex'
	size += len(a.CommitteeIndex) * 8

	// Field (3) 'Attestation'
	for ii := 0; ii < len(a.Attestation); ii++ {
		size += 4
		size += len(a.Attestation[ii])
	}

	// Field (4) 'Contributors'
	size += len(a.Contributors) * 112

	// Field (5) 'SubCommitteeIndexes'
	size += len(a.SubCommitteeIndexes) * 8

	// Field (6) 'SyncCommitteeSelectionProof'
	size += len(a.SyncCommitteeSelectionProof) * 160

	return
}

// HashTreeRoot ssz hashes the AggregatorConsensusData object
func (a *AggregatorConsensusData) HashTreeRoot() ([32]byte, error) {
	return ssz.HashWithDefaultHasher(a)
}

// HashTreeRootWith ssz hashes the AggregatorConsensusData object with a hasher
func (a *AggregatorConsensusData) HashTreeRootWith(hh ssz.HashWalker) (err error) {
	indx := hh.Index()

	// Field (0) 'Version'
	hh.PutUint64(uint64(a.Version))

	// Field (1) 'Aggregators'
	{
		subIndx := hh.Index()
		num := uint64(len(a.Aggregators))
		if num > 3000 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range a.Aggregators {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 3000)
	}

	// Field (2) 'CommitteeIndex'
	{
		if size := len(a.CommitteeIndex); size > 64 {
			err = ssz.ErrListTooBigFn("AggregatorConsensusData.CommitteeIndex", size, 64)
			return
		}
		subIndx := hh.Index()
		for _, i := range a.CommitteeIndex {
			hh.AppendUint64(i)
		}
		hh.FillUpTo32()
		numItems := uint64(len(a.CommitteeIndex))
		hh.MerkleizeWithMixin(subIndx, numItems, ssz.CalculateLimit(64, numItems, 8))
	}

	// Field (3) 'Attestation'
	{
		subIndx := hh.Index()
		num := uint64(len(a.Attestation))
		if num > 64 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range a.Attestation {
			{
				elemIndx := hh.Index()
				byteLen := uint64(len(elem))
				if byteLen > 1000000 {
					err = ssz.ErrIncorrectListSize
					return
				}
				hh.AppendBytes32(elem)
				hh.MerkleizeWithMixin(elemIndx, byteLen, (1000000+31)/32)
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 64)
	}

	// Field (4) 'Contributors'
	{
		subIndx := hh.Index()
		num := uint64(len(a.Contributors))
		if num > 12000 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range a.Contributors {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 12000)
	}

	// Field (5) 'SubCommitteeIndexes'
	{
		if size := len(a.SubCommitteeIndexes); size > 4 {
			err = ssz.ErrListTooBigFn("AggregatorConsensusData.SubCommitteeIndexes", size, 4)
			return
		}
		subIndx := hh.Index()
		for _, i := range a.SubCommitteeIndexes {
			hh.AppendUint64(i)
		}
		hh.FillUpTo32()
		numItems := uint64(len(a.SubCommitteeIndexes))
		hh.MerkleizeWithMixin(subIndx, numItems, ssz.CalculateLimit(4, numItems, 8))
	}

	// Field (6) 'SyncCommitteeSelectionProof'
	{
		subIndx := hh.Index()
		num := uint64(len(a.SyncCommitteeSelectionProof))
		if num > 4 {
			err = ssz.ErrIncorrectListSize
			return
		}
		for _, elem := range a.SyncCommitteeSelectionProof {
			if err = elem.HashTreeRootWith(hh); err != nil {
				return
			}
		}
		hh.MerkleizeWithMixin(subIndx, num, 4)
	}

	hh.Merkleize(indx)
	return
}

// GetTree ssz hashes the AggregatorConsensusData object
func (a *AggregatorConsensusData) GetTree() (*ssz.Node, error) {
	return ssz.ProofTree(a)
}
